[package]
name = "iwd-auto-timezone"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
dbus = "0.9.6"
dbus-tokio = "0.7.5"
futures-channel = "0.3.25"
futures-util = "0.3.25"
reqwest = "0.11.18"
tokio = { version = "1.28.2", features = ["full"] }
